server:
  port: 8080
spring:
  datasource:
      type: org.apache.commons.dbcp2.BasicDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.208.34.102:2397/pepper_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=3&serverTimezone=GMT%2B8
      username: pepper_test
      password: 1c783a89475060d1
      dbcp2:
        validation-query: SELECT 1
        max-conn-lifetime-millis: 3000


